GIT_URL = 'https://git.ajhs.io/alexsteffen/asearch'
GIT_BRANCH = 'master'
ISSUE_URL = 'https://git.ajhs.io/alexsteffen/asearch/issues'
SEARX_URL = 'https://searx.me'
DOCS_URL = 'https://searx.github.io/searx'
PUBLIC_INSTANCES = 'https://searx.space'
